const fs = require('fs');
const path = require('path');

// Simple bundler for Figma plugin
// Resolves imports and concatenates all JS files into one

function bundle() {
  console.log('🔨 Building plugin...');
  
  const srcDir = path.join(__dirname, 'src');
  const buildDir = path.join(__dirname, 'build', 'dsai-import-tokens');
  const outputFile = path.join(buildDir, 'code.js');
  const uiOutputFile = path.join(buildDir, 'ui.html');
  const manifestOutputFile = path.join(buildDir, 'manifest.json');
  
  // Create build directory if it doesn't exist
  if (!fs.existsSync(buildDir)) {
    fs.mkdirSync(buildDir, { recursive: true });
  }
  
  // Read main entry point
  const mainFile = path.join(srcDir, 'main.js');
  
  // Track processed modules to avoid duplicates
  const processedModules = new Set();
  const moduleContents = [];
  
  // Recursively process imports
  function processModule(filePath) {
    if (processedModules.has(filePath)) {
      return;
    }
    
    processedModules.add(filePath);
    
    let content = fs.readFileSync(filePath, 'utf-8');
    
    // Extract and process imports
    const importRegex = /import\s+{([^}]+)}\s+from\s+['"](.+?)['"]/g;
    let match;
    
    while ((match = importRegex.exec(content)) !== null) {
      const importPath = match[2];
      const absolutePath = path.resolve(path.dirname(filePath), importPath);
      
      // Process imported module first
      processModule(absolutePath);
    }
    
    // Remove import statements and export statements
    content = content.replace(/import\s+{[^}]+}\s+from\s+['"][^'"]+['"]\s*;?\n?/g, '');
    content = content.replace(/export\s+(async\s+)?function\s+/g, '$1function ');
    
    moduleContents.push({
      path: filePath,
      content: content.trim()
    });
  }
  
  // Process all modules starting from main
  processModule(mainFile);
  
  // Combine all modules
  let bundledCode = '// Auto-generated by build script - DO NOT EDIT DIRECTLY\n';
  bundledCode += '// Source files are in the src/ directory\n\n';
  
  for (const module of moduleContents) {
    const relativePath = path.relative(__dirname, module.path);
    bundledCode += `// ===== ${relativePath} =====\n\n`;
    bundledCode += module.content;
    bundledCode += '\n\n';
  }
  
  // Write bundled file
  fs.writeFileSync(outputFile, bundledCode, 'utf-8');
  console.log('✅ Generated:', path.relative(__dirname, outputFile));
  
  // Copy UI file
  const srcUiFile = path.join(srcDir, 'ui.html');
  if (fs.existsSync(srcUiFile)) {
    fs.copyFileSync(srcUiFile, uiOutputFile);
    console.log('✅ Copied:', path.relative(__dirname, uiOutputFile));
  }
  
  // Copy manifest file
  const srcManifestFile = path.join(__dirname, 'manifest.json');
  if (fs.existsSync(srcManifestFile)) {
    fs.copyFileSync(srcManifestFile, manifestOutputFile);
    console.log('✅ Copied:', path.relative(__dirname, manifestOutputFile));
  }
  
  console.log('✨ Build complete!');
  console.log('📦 Plugin ready at: build/dsai-import-tokens/');
}

// Run the bundler
try {
  bundle();
} catch (error) {
  console.error('❌ Build failed:', error.message);
  process.exit(1);
}
